name: CI/CD Deploy to EC2

# Kích hoạt workflow khi có push tới nhánh main
on:
  push:
    branches: [ "main" ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
  build-and-deploy:
    runs-on: ubuntu-latest  # Sử dụng runner Ubuntu
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # 1. Checkout mã nguồn
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 2. Cài JDK 17 và build ứng dụng (sử dụng Maven hoặc Gradle)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Java application
        run: mvn -B package --file pom.xml

      # 3. Đăng nhập Docker Hub (sử dụng thông tin trong Secrets)
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 4. Build Docker image và push lên Docker Hub
      - name: Build and Push Docker image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      # 5. Thiết lập SSH agent với private key (kết nối tới EC2)
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 6. SSH vào EC2 và triển khai container mới
      - name: Deploy on EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY_PATH }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
            docker stop myapp || true && docker rm myapp || true
            docker run -d --name myapp -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          EOF
